### ISSUE TITLE
Failing CI tests

### ISSUE THREAD

**Issue by ltfschoen** [DataHighway-DHX/node#32]
When the CI Test build runs cargo test in here https://github.com/DataHighway-DHX/node/runs/459859012, it's generating the following error:
```
   Compiling js-sys v0.3.35
error[E0603]: struct `Memory` is private
    --> /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/js-sys-0.3.35/src/lib.rs:4873:60
     |
4873 |                 let mem = buf.unchecked_ref::<WebAssembly::Memory>();
     |                                                            ^^^^^^ this struct is private
     |
note: the struct `Memory` is defined here
    --> /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/js-sys-0.3.35/src/lib.rs:3516:5
     |
3516 |     #[wasm_bindgen]
     |     ^^^^^^^^^^^^^^^
     = note: this error originates in an attribute macro (in Nightly builds, run with -Z macro-backtrace for more info)

```

**Comment by ltfschoen** [comment]
This could be because we're not installing the latest Rust versions in the CI Test section https://github.com/DataHighway-DHX/node/blob/master/.github/workflows/rust.yml#L55, only in the CI Linting section https://github.com/DataHighway-DHX/node/blob/master/.github/workflows/rust.yml#L86

**Comment by ltfschoen** [comment]
This is caused by https://github.com/rust-lang/rust/pull/69334, we've made changes here to try and fix it by using older versions of Rust Nightly that are known to work https://github.com/DataHighway-DHX/node/pull/29
